services:
  gateway:
    build: .
    image: gateway
    container_name: gateway
    env_file:
      - example.env
    ports:
      - "8000:80"
    networks:
      - gateway
    depends_on:
      pymongo_db:
        condition: service_started
      rabbitmq:
        condition: service_healthy

  pymongo_db:
    image: bitnami/mongodb:latest
    container_name: pymongo_db
    ports:
      - "27017:27017"
    networks:
      - gateway
    environment:
      - MONGODB_ROOT_PASSWORD=rootpassword

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    ports:
      - "5672:5672"
    networks:
      - gateway
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "-q", "check_running" ]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  gateway:
    name: gateway
